# Sesiunea 13 din modulul 13-14_NumPY – NumPy Începători
_Notebook de exerciții (fără soluții) din seria 13-14_NumPY, gândită pentru consolidarea noțiunilor de bază._


### Exercițiul 1 – Array 2D 5x5 cu valori random între 1 și 100
În cadrul recapitulării din modulul `13-14_NumPY`, exersăm generarea de date sintetice. Creează un array bidimensional (5x5) folosind `NumPy`, cu valori întregi aleatorii între 1 și 100, ideal cu `np.random.seed()` pentru reproductibilitate. Afișează rezultatul.

In [ ]:
import numpy as np

np.random.seed(42)

array = np.random.randint(1, 101, size=(5, 5))

print(array)

[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33]


### Exercițiul 2 – Media, maximul și minimul fiecărui rând
Continuând analiza setului creat la exercițiul precedent din seria `13-14_NumPY`, calculează media, valoarea maximă și valoarea minimă pentru fiecare rând folosind operații vectorizate.


In [7]:
import numpy as np

t1 = np.mean(array, axis=1)
t2 = np.max(array, axis=1)
t3 = np.min(array, axis=1)

print(t1, t2, t3, sep='\n')

[58.6 68.2 47.4 42.2 36. ]
[ 93  87 100  88  64]
[15 21  3  2  2]


### Exercițiul 3 – Funcție de normalizare a unui array
În ton cu secțiunea de prelucrare numerică din modulul `13-14_NumPY`, scrie o funcție `normalize(arr)` care primește un array și îl readuce în intervalul [0, 1]. Afișează array-ul normalizat pentru a verifica rezultatul.

In [13]:
import numpy as np

def normalize(array):
    min_val = np.min(array)
    max_val = np.max(array)

    normalized = (array - min_val) / (max_val - min_val)
    return normalized

print(normalize(array))

[[0.51020408 0.92857143 0.13265306 0.71428571 0.60204082]
 [0.19387755 0.82653061 0.86734694 0.74489796 0.74489796]
 [0.87755102 1.         0.2244898  0.01020408 0.20408163]
 [0.52040816 0.         0.87755102 0.28571429 0.36734694]
 [0.         0.63265306 0.59183673 0.19387755 0.31632653]]


### Exercițiul 4 – Produs scalar între două array-uri
Revenind la conceptele de algebra liniară discutate în `13-14_NumPY`, creează două array-uri 1D de aceeași lungime și calculează produsul lor scalar folosind `np.dot()`.

In [15]:
import numpy as np

a = np.array([5, 78, 9])
b = np.array([1, 0, 10])

print(np.dot(a, b))

95


### Exercițiul 5 – Verificare simetrie matrice pătratică
Pentru a încheia tema despre matrici din modulul `13-14_NumPY`, scrie o funcție care verifică dacă o matrice pătratică este simetrică (egală cu transpusul ei) și testeaz-o pe un exemplu concret.

In [16]:
import numpy as np

def is_symmetric(matrix):
    return np.array_equal(matrix, matrix.T)

A = np.array([
    [1, 2, 3],
    [2, 5, 6],
    [3, 6, 9]
])

print("array symmetric: ", is_symmetric(A))

array symmetric:  True
