# Sesiunea 14 – NumPy Avansat
_Notebook de exerciții (fără soluții)._

## Exercițiu 1 – Broadcasting cu bias
Creează un array `img` 3x3 și un vector `bias`, apoi aplică biasul pe fiecare rând folosind broadcasting.

Exemplu:
```python
img = np.array([[10,20,30],[40,50,60],[70,80,90]])
bias = np.array([1, 0, -1])
```
Afișează rezultatul lui `img + bias`.

In [4]:
import numpy as np

img = np.array([[10,20,30],[40,50,60],[70,80,90]])
bias = np.array([1, 0, -1])

print(img + bias)

[[11 20 29]
 [41 50 59]
 [71 80 89]]


## Exercițiu 2 – Indexare logică
Creează un array 1D de valori numerice. Folosește o mască logică pentru a extrage doar elementele care respectă o anumită condiție (de exemplu, valori mai mari de 25).

In [7]:
import numpy as np

array = np.array([10, 30, 20, 40])
mask = array > 25
filtered = array[mask]

print(filtered)

[30 40]


## Exercițiu 3 – Funcții matematice și agregări
Creează un vector `x` folosind `np.linspace(0, 10, 100)`. Calculează `sin(x)`, apoi media și deviația standard.

În plus, aplică operații de agregare pe o matrice 2D folosind `axis=0` și `axis=1`.

In [15]:
import numpy as np

x = np.linspace(0, 10, 50)
print(x, '\n')

wave = np.sin(x)
mean = np.mean(wave)
std = np.std(wave)

print(wave, mean, std, sep='\n\n')

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] 

[ 0.          0.20266794  0.39692415  0.57470604  0.72863478  0.85232157
  0.94063279  0.98990308  0.99808748  0.96484631  0.89155923  0.78126802
  0.63855032  0.46932961  0.2806294   0.08028167 -0.12339814 -0.32195632
 -0.50715171 -0.67129779 -0.80758169 -0.91034694 -0.97532829 -0.99982867
 -0.9828312  -0.92504137 -0.82885774 -0.6982724  -0.53870529 -0.35677924
 -0.16004509  0.0433317

In [26]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

wave = np.sin(x)
mean = np.mean(wave, axis=0)
std = np.std(wave, axis=0)

print(x, wave, mean, std, sep='\n\n')
print('\n---\n')

wave = np.sin(x)
mean = np.mean(wave, axis=1)
std = np.std(wave, axis=1)

print(x, wave, mean, std, sep='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[0.24721836 0.3132438  0.09127433]

[0.71393372 0.90015226 0.28450923]

---

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[ 0.63062947 -0.66504742  0.68615444]

[0.34724126 0.28489447 0.23655797]


## Exercițiu 4 – Normalizare pe axă
Normalizează o matrice 2x2 folosind formula:

\[ norm = (m - media) / std \]

unde media și deviația standard sunt calculate pe coloane (`axis=0`).

In [35]:
import numpy as np

arr = np.array([
    [2, 8],
    [4, 6]
])

mean = np.mean(arr, axis=0)
std = np.std(arr, axis=0)

print((arr - mean) / std)
print()

mean = np.mean(arr, axis=1)
std = np.std(arr, axis=1)

print((arr - mean) / std)

[[-1.  1.]
 [ 1. -1.]]

[[-1.          3.        ]
 [-0.33333333  1.        ]]


## Exercițiu 5 – Manipulare avansată de array-uri
Creează un vector `v` cu 12 elemente, transformă-l într-o matrice 3x4. Aplică:
- `np.hsplit()` pentru a-l împărți pe coloane
- `np.vstack()` pentru a concatena două copii ale matricei pe verticală.

In [ ]:
import numpy as np

v = np.arange(12)
m = v.reshape(3, 4)

cols = np.hsplit(m, 2)
stacked = np.vstack((m, m))

print(stacked)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Exercițiu 6 – Vectorizare vs For-loop
Generează un milion de numere și calculează pătratele lor:
- o dată folosind un for-loop
- o dată folosind operații vectorizate cu NumPy
Compară timpul de execuție între cele două metode.

In [28]:
import random
import numpy as np
import time

numbers = [random.randint(0, 1_000) for _ in range(1_000_000)]
start = time.perf_counter()
squared_numbers = [x ** 2 for x in numbers]
first = time.perf_counter() - start

print(first, squared_numbers[:10], sep='\n')
print()

numbers_array = np.random.randint(0, 1_000, 1_000_000)
start = time.perf_counter()
squared_numbers_array = np.square(numbers_array)
second = time.perf_counter() - start

print(second, squared_numbers_array[:10], sep='\n')
print()

print("NumPy is", first / second, "times more effcient")

0.09190200399825699
[262144, 727609, 11449, 35344, 617796, 419904, 698896, 291600, 205209, 385641]

0.0025245189972338267
[172225  11881 345744 714025 355216 404496 294849 603729 158404    784]

NumPy is 36.40376804411301 times more effcient


## Exercițiu 7 – Distanță euclidiană vectorizată
Calculează distanța euclidiană dintre doi vectori `p1` și `p2` fără a folosi bucle.

`dist = ((np.sum((p1 - p2) ** 2)) ** 0.5)`

In [33]:
p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])

dist = ((np.sum((p1 - p2) ** 2)) ** 0.5)
print(dist)

5.196152422706632


## Exercițiu 8 – Big Arrays și filtrare
Generează un array de 10 milioane de numere întregi aleatoare între 1 și 20000.
Selectează doar valorile mai mari de 10000 și calculează media acestora.

In [ ]:
# using list comprehensions and generator expressions
import random

numbers = [random.randint(1, 20_000) for _ in range(10_000_000)]
mask = [(x, x > 10_000) for x in numbers]

filtered = [x[0] for x in mask if x[1]]
mean_numbers = sum(x for x in numbers if x > 10_000) / sum(1 for x in numbers if x > 10_000)

print(filtered[:10])
print(mean_numbers)

[12929, 15679, 14535, 10276, 16281, 13106, 16638, 13226, 11708, 13624]
15000.058288284901


In [ ]:
# using numpy
import numpy as np

numbers = np.random.randint(1, 20_000, 10_000_000)
mask = numbers > 10_000

filtered = numbers[mask]
print(filtered[:10])

[16559 12417 18801 19857 16808 16980 10881 10257 18980 19156]


## Exercițiu 9 – Exerciții practice
- Generează 1 milion de numere aleatoare și calculează suma celor divizibile cu 7.
- Normalizează o matrice 1000x1000.
- Simulează o imagine RGB 1920x1080 și înmulțește fiecare pixel cu 1.5.
- Creează o matrice 3D și calculează suma pe axa Z (`axis=2`).

# Generează 1 milion de numere aleatoare și calculează suma celor divizibile cu 7

In [58]:
import random

numbers = [random.randint(0, 10_000) for _ in range(1_000_000)]
divisible = [x for x in numbers if not x % 7]

print(sum(divisible))

711953473


In [62]:
import numpy as np

numbers = np.random.randint(0, 10_000, 1_000_000)
mask = numbers % 7 == 0
divisible = numbers[mask]

print(sum(divisible))

715552187


# Normalizează o matrice 1000x1000

In [68]:
import numpy as np

def normalize(array):
    min_val = np.min(array)
    max_val = np.max(array)

    normalized = (array - min_val) / (max_val - min_val)
    return normalized

matrix = np.random.randint(0, 101, size=(1000, 1000))
print(normalize(matrix))

[[0.01 0.49 0.46 ... 0.83 0.3  0.17]
 [0.1  0.18 0.04 ... 0.33 0.57 0.59]
 [0.56 0.85 0.59 ... 0.46 0.76 0.87]
 ...
 [0.45 0.34 0.86 ... 0.13 0.38 0.86]
 [0.92 0.19 0.45 ... 0.84 0.12 0.36]
 [0.79 0.95 0.76 ... 0.45 0.24 0.51]]


# Simulează o imagine RGB 1920x1080 și înmulțește fiecare pixel cu 1.5

In [4]:
import cv2
import numpy as np

img = np.random.randint(0, 256, size=(1080, 1920, 3))
img_multiplied = np.clip(img * 1.5, 0, 255)

img = img.astype(np.uint8)
img_multiplied = img_multiplied.astype(np.uint8)

cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.imshow("Image2", img_multiplied)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Creează o matrice 3D și calculează suma pe axa Z (`axis=2`)

In [33]:
import numpy as np

coords = np.random.randint(0, 256, size=(16, 16, 384), dtype=np.uint8)

print(coords.shape)
sum_z = np.sum(coords, axis=2)
print(sum_z)
print(round(coords.nbytes), "Bytes")

(16, 16, 384)
[[46887 48690 48622 50684 47679 47444 50752 50568 47336 47112 48522 49090
  48327 47565 52380 52650]
 [47377 48388 50182 48350 50948 50205 49398 49084 50788 50971 48907 50545
  51762 48614 51310 49710]
 [46701 49481 48141 50061 46478 50105 49932 47880 45915 46658 47533 49485
  49195 50445 46297 49340]
 [48933 50474 49515 47133 49213 50577 49408 48865 50112 51220 45958 46560
  51680 50169 51158 48125]
 [47238 48117 50076 51452 50372 50114 48167 50559 45852 48630 48137 50316
  47262 49981 50367 48282]
 [50172 46317 49389 50674 48838 49491 49801 50360 50251 48706 50220 48986
  48357 49836 51301 51403]
 [48305 49499 48039 50876 47174 48483 48089 48629 48951 47432 48500 49154
  47618 50466 48652 50379]
 [46658 49969 47808 48287 47254 50756 49402 49357 51415 48703 48511 49903
  47863 53163 51180 49339]
 [48867 50202 49945 49042 47309 47427 49253 50652 51381 51765 49163 48216
  46479 50378 45776 51760]
 [49484 46540 47301 47461 50453 48123 47995 49829 48629 49117 48553 48831
  4